import { B512RecordTypesMap, RecordDefinition } from '../../types/validation'

export const B512_RECORD_TYPE_MAP: B512RecordTypesMap = {
  A00: {
    optional: false,
    minCount: 1,
    maxCount: 0,
    level: '01',
    fields: [
      {
        fieldName: "Satzart 'A00'",
        optional: false,
        length: 3,
        decimal: 1,
        from: 1,
        to: 3,
        remark: 'Konstant A00',
      },
      {
        fieldName: 'Qualifier Datenart',
        optional: false,
        length: 3,
        decimal: null,
        from: 4,
        to: 6,
        remark: 'STD, KDF, ABH, CLU, GTW',
      },
      {
        fieldName: 'Releasestand',
        optional: false,
        length: 3,
        decimal: null,
        from: 7,
        to: 9,
        remark: '100',
      },
      {
        fieldName: 'Bordero-Nummer',
        optional: false,
        length: 35,
        decimal: 0,
        from: 10,
        to: 44,
        remark: '',
      },
      {
        fieldName: 'Borderodatum (TTMMJJJJ)',
        optional: false,
        length: 8,
        decimal: null,
        from: 45,
        to: 52,
        remark: '',
      },
      {
        fieldName: 'Verkehrsart',
        optional: true,
        length: 3,
        decimal: null,
        from: 53,
        to: 55,
        remark: 'siehe Codeliste, muss bei STD, nicht verwendet bei ABH',
      },
      {
        fieldName: 'Produkt',
        optional: true,
        length: 3,
        decimal: null,
        from: 56,
        to: 58,
        remark:
          'siehe Codeliste, kann bei direkten Verkehren ohne zentralen Dienstleister entfallen.',
      },
      {
        fieldName: 'Codeliste (Kooperation)',
        optional: false,
        length: 3,
        decimal: null,
        from: 59,
        to: 61,
        remark: 'Kennzeichen für die verwendete Codelisten (SYA bei System Alliance)',
      },
      {
        fieldName: 'Währung',
        optional: false,
        length: 3,
        decimal: null,
        from: 62,
        to: 64,
        remark: 'nach ISO',
      },
      {
        fieldName: 'Identifikation des Versenders des Borderos',
        optional: true,
        length: 35,
        decimal: null,
        from: 65,
        to: 99,
        remark: 'Kunde bei KDF, AP bei ABH, VP bei STD',
      },
      {
        fieldName: 'Identifikation des Empfängers des Borderos',
        optional: true,
        length: 35,
        decimal: null,
        from: 100,
        to: 134,
        remark: 'VP bei KDF, VP bei ABH, EP bei STD',
      },
      {
        fieldName: 'Frachtführer',
        optional: true,
        length: 35,
        decimal: null,
        from: 135,
        to: 169,
        remark: '',
      },
      {
        fieldName: 'Frachtführer Land',
        optional: true,
        length: 3,
        decimal: null,
        from: 170,
        to: 172,
        remark: '',
      },
      {
        fieldName: 'Frachtführer PLZ',
        optional: true,
        length: 9,
        decimal: null,
        from: 173,
        to: 181,
        remark: '',
      },
      {
        fieldName: 'Frachtführer Ort',
        optional: true,
        length: 35,
        decimal: null,
        from: 182,
        to: 216,
        remark: '',
      },
      {
        fieldName: 'KFZ Kennzeichen 1',
        optional: true,
        length: 35,
        decimal: null,
        from: 217,
        to: 251,
        remark: '',
      },
      {
        fieldName: 'KFZ Kennzeichen 2',
        optional: true,
        length: 35,
        decimal: null,
        from: 252,
        to: 286,
        remark: '',
      },
      {
        fieldName: 'Weiterleitungs Id 1',
        optional: true,
        length: 35,
        decimal: null,
        from: 287,
        to: 321,
        remark:
          'Jeder der eingetragenen Weiterleitungs Ids erhält eine Kopie des Borderos, wenn das Bordero z.B. über ein zentrales Rechenzentrum versendet wird.',
      },
      {
        fieldName: 'Weiterleitungs Id 2',
        optional: true,
        length: 35,
        decimal: null,
        from: 322,
        to: 356,
        remark: '',
      },
      {
        fieldName: 'Testkennzeichen',
        optional: true,
        length: 1,
        decimal: 0,
        from: 357,
        to: 357,
        remark: 'Testdaten müssen per Y markiert werden',
      },
    ],
  },
}
